### ISSUE TITLE
移动端支持

### ISSUE THREAD

**Issue by jessjava** [GinMu/vue-audio#3]
移动端支持较差，第一次加载音频时一直在 waiting

**Comment by GinMu** [comment]
公司项目忙，这段时间没有时间维护，欢迎提交request

**Comment by jessjava** [comment]
不知道哪里的问题。还在找。

**Comment by GinMu** [comment]
更新了代码，如果一直waiting可以试着修改下preload值

**Comment by jessjava** [comment]
1. preload 解决了移动端的加载不播放问题。多谢。
2. 移动端还有个问题：
`下一个音频没有加载过时，上一个点击播放之后下一个就无法自动播放`；
`如果下一个音频加载过（播放过 或 播放终止过），上一个点击播放完之后下一个就可以自动播放`
`我猜这个问题是移动端不支持代码 audio.play()调用  ，必须由事件触发才可以，您有解决办法吗。`

**Comment by GinMu** [comment]
不是不支持audio.play()调用，应该是触发了error事件

**Comment by jessjava** [comment]
有什么解决办法不

**Comment by jessjava** [comment]
没有触发error事件

**Comment by GinMu** [comment]
应该是移动端浏览器限制问题，正在查资料，欢迎一起解决
